### ISSUE TITLE
 TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-experiment#11]
### Information

- **Qiskit IBM Provider version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
It seems that `provider.experiment.create_analysis_result` fails if the input has a NumPy `int64` value.

**Comment by gadial** [comment]
I am not able to reproduce the problem. Passing `np.int64(n)` for some `n` does not result in failing; I extended the `test_analysis_result_coders` test to use this datatype as well, and it passes.

One thing to note: when converting `int64` to json string, it is implicitly converted to array, meaning we the following code
```
d = {'num': np.int64(42)}
s = json.dumps(d, cls=ExperimentEncoder)
print(s)
res = json.loads(s, cls=ExperimentDecoder)
print(res)
print(type(res['num']))
```

Results in
```
{"num": {"__type__": "array", "__value__": 42}}
{'num': array(42)}
<class 'numpy.ndarray'>
```

This should not pose a problem, but it is not a direct conversion.
