### ISSUE TITLE
Misc cleanup and general change suggestions

### ISSUE THREAD

**Issue by eliarbel** [Qiskit/qiskit-ibm-experiment#12]
## Cleanup 
* requirements.txt and especially requirements-dev.txt - do we need everything there ? Some dependencies may be redundant (e.g. mthree in dev reqs - is it really needed?)
* tools/deploy_documentation.sh - the script is written for runtime docs, need to be adapted or removed 
* qiskit_ibm_experiment
	* constants.py - QISKIT_IBM_RUNTIME_API_URL - is it the right URL/name for the experiment service API ? 
	* client/session.py - some runtime related constants. Should they adjusted for the experiments service or removed ?
 
##  Simple changes
* Documentation
   * Update CONTRIBUTING.md for the repo
   * Write some informative text in README.md
* Change the 'experiment' folder name to 'service'.

**Comment by gadial** [comment]
Done in #20
