### ISSUE TITLE
Experiment integration tests should limit query to qiskit_test only

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-experiment#15]
### Information

- **Qiskit IBM Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
A follow up to Qiskit/qiskit-ibm-provider#112. Tests in `TestExperimentServerIntegration` should always use `experiment_type='qiskit_test'` as a filter whenever applicable.

**Comment by gadial** [comment]
Fixed in #20
