### ISSUE TITLE
Make prompting optional when deleting experiments

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-experiment#16]
### What is the expected enhancement?

Delete an experiment data / analysis result / figure today would prompt the user for confirmation. This makes it difficult for `qiskit-experiments` to automatically delete old data when analysis is re-run, especially for composite experiments that could have a lot of old data. 

We can instead make this an option - e.g. `IBMExperimentService.set_option(prompt_for_delete=False)`, with `True` being the default. So those who use the experiment service directly will continue to get prompted, and `qiskit-experiments` can set it to False.

**Comment by gadial** [comment]
Done in #23
