### ISSUE TITLE
Bugs in the local service

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-ibm-experiment#46]
# 1.

I have qiskit-experiments code that runs on simulator and saves the results to the `FakeService` of qiskit-experiments. It turns out that the fake service cannot be used anymore:
```
Unable to save the experiment data: Traceback (most recent call last):
  File "/home/hrlquantum/work/experiments/System/qiskit_experiments/framework/experiment_data.py", line 1358, in _save_experiment_metadata
    self.service.create_or_update_experiment(
AttributeError: 'FakeService' object has no attribute 'create_or_update_experiment'
```

# 2.

So I decided to try to switch to the local service:
```
service = IBMExperimentService(local=True, local_save=False)
```

(by the way note inconsistency between parameters and doc string [here](https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/client/local_client.py#L69-L75)).

The following line in my code failed:
```
experiments = self.service.experiments(
            limit=None,
            backend_name=self._backend_name,
            tags=["hey there"],
            tags_operator="AND",
            start_datetime_after=start_datetime_after,
            sort_by=["start_datetime:asc"],
            mine_only=mine_only,
        )
```
With the error message:
```
      File "/home/hrlquantum/miniconda3/envs/env1/lib/python3.9/site-packages/qiskit_ibm_experiment/service/ibm_experiment_service.py", line 648, in experiments
    response = self._api_client.experiments(

      File "/home/hrlquantum/miniconda3/envs/env1/lib/python3.9/site-packages/qiskit_ibm_experiment/client/local_client.py", line 307, in experiments
    raise ValueError(

    ValueError: The fake service currently supports only sorting by start_datetime, which can be either asc or desc
```

So I downloaded my clone of qiskit-ibm-experiment and debugged it. At some point (probably [here](https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/service/ibm_experiment_service.py#L637)) `start_datetime` becomes `start_time`. Therefore when we reach https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/client/local_client.py#L300-L310 The value of `sort_by[0]` is `start_time:asc`, hence the error. In my clone I fixed the check to trigger the error if `sortby_split[0] != "start_time"`.

(by the way note that the [docs](https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/service/ibm_experiment_service.py#L577-L586) say semicolon instead of colon).

# 3.
The call to `experiments` stopped crashing, but it unexpectedly returns 0 experiments. The debug reveals that the problem is in the filtering by tags: https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/client/local_client.py#L270-L280

The code here expects the tags to be in the same format as in the call to `experiments`, i.e., a list of strings. But `experiments` converts all the tags, together with the `tags_operator`, into a single string: https://github.com/Qiskit/qiskit-ibm-experiment/blob/9612bcb58969bec9bdb10732e1a35715eeecfea5/qiskit_ibm_experiment/service/ibm_experiment_service.py#L1118-L1127

By the time we reach the filtering in the local client, we have `tags_operator`always set to `"OR"`, and `tags` set to `contains:hey there`. So I fixed the filtering:
```
        if tags is not None:
            # Remove "contains:" prefix
            tags_as_list = tags.split(":")
            is_or = (tags_as_list[0] == "any")
            tags_as_list = tags_as_list[1].split(",")
            if is_or:
                df = df.loc[
                    df.tags.apply(lambda dftags: any(x in dftags for x in tags_as_list))
                ]
            else:
                df = df.loc[
                    df.tags.apply(lambda dftags: all(x in dftags for x in tags_as_list))
                ]
```

# 4.

Now `experiments` runs and returns the correct number of experiments. My code, that's supposed to run mostly on devices, expects the output of `experiments` to be in the form of a dictionary. But the new service returns `ExperimentData`. This means that, as long as the devices user the old service, I cannot use the local service when running on a simulator (unless I make the effort of modifying my code to support two formats of return values of `experiments`). And I can't use the fake service either, as noted in the beginning.

**Comment by gadial** [comment]
1. Indeed, `FakeService` is not compatible with the new version of `qiskit_experiments`.
2. The inconsistency you point out is actually ok; when you call `IBMExperimentService` you don't generate the client yourself; it's created by `IBMExperimentService`. When specifying `local=True` you tell it to use the local client class, instead of the web API class.
3. There is indeed a big problem with filtering by dates; I'll push a fix soon and it will also be included in the new release of `qiskit-experiments`.
4. This is an unfortunate side effect of the move to dataclasses; while we can hack around it, indeed the best solution would be to use the new service system-wide.
