### ISSUE TITLE
Many tests are skipped: Only runs on staging

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-ibm-experiment#49]
**Describe the bug**
I do run them on the staging directory, so it isn't clear why are they skipped.

**Steps to reproduce**
regular build/tests

**Additional Information**

- **Qiskit IBM Runtime version**: 0.2.5
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.1

**Comment by gadial** [comment]
This happened because the url of  the server was changed; it's fixed now and all the tests are passing.
